#include "repository.h"
#include <windows.h>
#include <commctrl.h>
#include <shlobj.h>
#include <shellapi.h>
#include <thread>
#include <mutex>
#include <stdexcept>
#include <fstream>
#include <iostream>
using namespace lite;
namespace {
constexpr UINT OUTPUT=WM_APP+1,DONE=WM_APP+2,REVIEW=WM_APP+3,STATE=WM_APP+4;
HWND window,repoEdit,statusEdit,logEdit,checkCombo,actionCombo,remoteEdit,refEdit,detailsEdit,runButton,actionButton,cancelButton,activityLabel;
HFONT uiFont,monoFont; Runner runner; Settings settings; fs::path config,repo,logPath,dataDir;std::thread worker;std::atomic<bool> busy{false};std::mutex outputMutex;std::string pending;std::vector<Check> checks; bool smoke=false;int smokePhase=0,smokeExit=0,smokeTicks=0;
enum {BROWSE=101,SELECT,REFRESH,RUN,ACTION,CANCEL,LOGS,CONFIG,AGENTS};
const std::vector<std::string> actions={"Fetch","Pull (fast-forward)","Merge","Rebase","Stage paths","Commit staged","Push reviewed","Compare upstreams","Upstream diff","Add remote","PR readiness","PR checks","Create draft PR"};
std::string value(HWND h){int n=GetWindowTextLengthW(h);std::wstring s(n+1,0);GetWindowTextW(h,s.data(),n+1);s.resize(n);return utf8(s);}
void set(HWND h,const std::string&s){auto t=wide(s);SetWindowTextW(h,t.c_str());}
void append(HWND h,std::string s){ // Logs are UTF-8; malformed tool bytes are replaced for display only.
    int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring t(n,0);MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),t.data(),n);
    std::wstring cr;for(size_t i=0;i<t.size();++i){if(t[i]=='\n'&&(i==0||t[i-1]!='\r'))cr+='\r';cr+=t[i];}
    if(GetWindowTextLengthW(h)>750000)SetWindowTextW(h,L"[Earlier output is in the complete durable log.]\r\n");SendMessageW(h,EM_SETSEL,-1,-1);SendMessageW(h,EM_REPLACESEL,FALSE,(LPARAM)cr.c_str());
}
void output(const std::string&s){std::lock_guard<std::mutex> lock(outputMutex);pending+=s;PostMessageW(window,OUTPUT,0,0);}
bool approve(const std::string&s){return SendMessageW(window,REVIEW,0,(LPARAM)&s)!=0;}
struct ReviewState { bool done=false,approved=false;HWND text,yes,no;HFONT font; };
LRESULT CALLBACK ReviewProc(HWND h,UINT m,WPARAM w,LPARAM l){auto*p=(ReviewState*)GetWindowLongPtrW(h,GWLP_USERDATA);if(m==WM_NCCREATE){p=(ReviewState*)((CREATESTRUCTW*)l)->lpCreateParams;SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)p);}if(!p)return DefWindowProcW(h,m,w,l);
    if(m==WM_SIZE){int x=LOWORD(l),y=HIWORD(l);MoveWindow(p->text,16,16,x-32,y-78,TRUE);MoveWindow(p->yes,x-300,y-48,140,32,TRUE);MoveWindow(p->no,x-150,y-48,130,32,TRUE);return 0;}
    if(m==WM_COMMAND){p->approved=LOWORD(w)==1;p->done=true;DestroyWindow(h);return 0;}if(m==WM_CLOSE){p->done=true;DestroyWindow(h);return 0;}return DefWindowProcW(h,m,w,l);
}
bool reviewDialog(const std::string&text){if(smoke)throw std::runtime_error("Smoke test must never approve a mutation");ReviewState st;
    HWND h=CreateWindowExW(WS_EX_DLGMODALFRAME,L"TangOSLiteReview",L"TangOS Lite - Review every change",WS_OVERLAPPEDWINDOW|WS_VISIBLE, CW_USEDEFAULT,CW_USEDEFAULT,940,720,window,nullptr,GetModuleHandleW(nullptr),&st);
    st.text=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_MULTILINE|ES_READONLY|WS_VSCROLL|WS_HSCROLL|ES_AUTOHSCROLL,16,16,890,580,h,nullptr,nullptr,nullptr);SendMessageW(st.text,EM_SETLIMITTEXT,64*1024*1024,0);SendMessageW(st.text,WM_SETFONT,(WPARAM)monoFont,TRUE);
    set(st.text,text);st.yes=CreateWindowW(L"BUTTON",L"Approve operation",WS_CHILD|WS_VISIBLE|WS_TABSTOP,620,610,140,32,h,(HMENU)1,nullptr,nullptr);st.no=CreateWindowW(L"BUTTON",L"Cancel",WS_CHILD|WS_VISIBLE|WS_TABSTOP,770,610,130,32,h,(HMENU)2,nullptr,nullptr);SendMessageW(st.yes,WM_SETFONT,(WPARAM)uiFont,TRUE);SendMessageW(st.no,WM_SETFONT,(WPARAM)uiFont,TRUE);
    EnableWindow(window,FALSE);SetFocus(st.no);MSG msg;while(!st.done&&GetMessageW(&msg,nullptr,0,0)>0){if(!IsDialogMessageW(h,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}}EnableWindow(window,TRUE);SetForegroundWindow(window);return st.approved;
}
void fillChecks(){checks=discoverChecks(repo,settings);SendMessageW(checkCombo,CB_RESETCONTENT,0,0);for(auto&c:checks){auto s=wide(c.name+(c.available?"":" [unavailable]"));SendMessageW(checkCombo,CB_ADDSTRING,0,(LPARAM)s.c_str());}SendMessageW(checkCombo,CB_SETCURSEL,smoke?2:0,0);}
void start(const std::function<void()>& job){if(busy)return;if(worker.joinable())worker.join();runner.reset();busy=true;EnableWindow(runButton,FALSE);EnableWindow(actionButton,FALSE);EnableWindow(cancelButton,TRUE);set(activityLabel,"Running - output saved continuously. Cancel stops the process tree.");worker=std::thread([job]{try{job();}catch(const std::exception&e){output("\nERROR: "+std::string(e.what())+"\n");if(smoke)smokeExit=1;}PostMessageW(window,DONE,0,0);});}
void selectRepo(){auto selected=fs::u8path(value(repoEdit));start([selected]{Repository r(runner,selected,settings);repo=r.root;settings.repository=utf8(repo.wstring());saveSettings(config,settings);auto s=new std::string(r.status());PostMessageW(window,STATE,0,(LPARAM)s);});}
void refresh(){if(repo.empty())return;start([]{Repository r(runner,repo,settings);auto s=new std::string(r.status());PostMessageW(window,STATE,0,(LPARAM)s);});}
void runCheck(){if(repo.empty())return;auto i=(size_t)SendMessageW(checkCombo,CB_GETCURSEL,0,0);start([i]{Repository r(runner,repo,settings);auto c=r.check(i);if(!smoke&&!approve("Run repository code? Review this command and trust its script first. Repository scripts can write files; this is not a sandbox.\n\n"+preview(c)+"\n\nRequires: "+checks[i].requirement))return;logPath=dataDir/"logs"/(uniqueId()+"-check.log");output("Complete log: "+utf8(logPath.wstring())+"\n");auto result=runner.run(c,output,logPath);if(smoke&&result.code)smokeExit=1;});}
void runAction(){if(repo.empty())return;auto idx=(size_t)SendMessageW(actionCombo,CB_GETCURSEL,0,0);if(idx>=actions.size())return;auto name=actions[idx],remote=value(remoteEdit),ref=value(refEdit),details=value(detailsEdit);start([name,remote,ref,details]{Repository r(runner,repo,settings);auto c=r.action(name,remote,ref,details);std::string approvedSnapshot;
    if(name=="Commit staged"){approvedSnapshot=r.commitPreview();if(!approve("COMMIT STAGED\nMessage: "+details+"\n\n"+approvedSnapshot))return;if(r.commitPreview()!=approvedSnapshot)throw std::runtime_error("Index changed after review. Preview again.");}
    else if(name=="Push reviewed"){approvedSnapshot=r.pushPreview(remote,ref);if(!approve("PUSH - review every outgoing commit below. Fetch before review to refresh remote state.\n\n"+approvedSnapshot))return;if(r.pushPreview(remote,ref)!=approvedSnapshot)throw std::runtime_error("Outgoing commits changed after review. Preview again.");}
    else if(name=="Merge"||name=="Rebase"||name=="Pull (fast-forward)"||name=="Stage paths"||name=="Add remote"||name=="Create draft PR"){if(!approve("Confirm "+name+"\n\n"+preview(c)+"\n\n"+details+"\n\nMerge/rebase can change source files. Git hooks are repository-owned code. Resolve conflicts with Git outside Lite. No force/reset/clean operation is offered."))return;c=r.action(name,remote,ref,details);}
    logPath=dataDir/"logs"/(uniqueId()+"-git.log");output("Complete log: "+utf8(logPath.wstring())+"\n");runner.run(c,output,logPath);
});}
HWND control(const wchar_t*className,const wchar_t*text,DWORD style,int id=0){HWND h=CreateWindowExW(className==std::wstring(L"EDIT")?WS_EX_CLIENTEDGE:0,className,text,WS_CHILD|WS_VISIBLE|style,0,0,100,30,window,(HMENU)(INT_PTR)id,GetModuleHandleW(nullptr),nullptr);SendMessageW(h,WM_SETFONT,(WPARAM)uiFont,TRUE);return h;}
HWND titleLabel,repoLabel,checkLabel,actionLabel,remoteLabel,refLabel,detailLabel,statusLabel,logLabel,browseButton,selectButton,refreshButton,logsButton,configButton,agentsButton;
void layout(int w,int h){int margin=18,gap=10;MoveWindow(titleLabel,margin,12,w-36,32,TRUE);MoveWindow(repoLabel,margin,51,100,22,TRUE);MoveWindow(repoEdit,margin,76,w-326,30,TRUE);MoveWindow(browseButton,w-298,76,82,30,TRUE);MoveWindow(selectButton,w-206,76,86,30,TRUE);MoveWindow(refreshButton,w-110,76,92,30,TRUE);
    MoveWindow(checkLabel,margin,120,100,22,TRUE);MoveWindow(checkCombo,margin,145,350,300,TRUE);MoveWindow(runButton,378,145,110,30,TRUE);MoveWindow(cancelButton,498,145,100,30,TRUE);MoveWindow(logsButton,w-260,145,115,30,TRUE);MoveWindow(configButton,w-135,145,117,30,TRUE);
    MoveWindow(actionLabel,margin,188,110,22,TRUE);MoveWindow(actionCombo,margin,213,220,380,TRUE);MoveWindow(remoteLabel,248,188,230,22,TRUE);MoveWindow(remoteEdit,248,213,230,30,TRUE);MoveWindow(refLabel,488,188,230,22,TRUE);MoveWindow(refEdit,488,213,w-736,30,TRUE);MoveWindow(actionButton,w-238,213,105,30,TRUE);MoveWindow(agentsButton,w-123,213,105,30,TRUE);
    MoveWindow(detailLabel,margin,255,500,22,TRUE);MoveWindow(detailsEdit,margin,278,w-36,60,TRUE);int left=std::max(300,w/3);MoveWindow(statusLabel,margin,350,left,22,TRUE);MoveWindow(logLabel,left+gap+margin,350,w-left-54,22,TRUE);MoveWindow(statusEdit,margin,375,left,h-429,TRUE);MoveWindow(logEdit,left+gap+margin,375,w-left-54,h-429,TRUE);MoveWindow(activityLabel,margin,h-40,w-36,26,TRUE);
}
void browse(){IFileDialog* d=nullptr;if(SUCCEEDED(CoCreateInstance(CLSID_FileOpenDialog,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&d)))){DWORD opts;d->GetOptions(&opts);d->SetOptions(opts|FOS_PICKFOLDERS|FOS_FORCEFILESYSTEM);if(SUCCEEDED(d->Show(window))){IShellItem*i=nullptr;if(SUCCEEDED(d->GetResult(&i))){PWSTR p=nullptr;if(SUCCEEDED(i->GetDisplayName(SIGDN_FILESYSPATH,&p))){SetWindowTextW(repoEdit,p);CoTaskMemFree(p);selectRepo();}i->Release();}}d->Release();}}
LRESULT CALLBACK WindowProc(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:{window=h;uiFont=CreateFontW(-16,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");monoFont=CreateFontW(-14,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,FIXED_PITCH,L"Consolas");
    titleLabel=control(L"STATIC",L"TangOS Lite   |   native repository workbench",0);repoLabel=control(L"STATIC",L"Repository",0);repoEdit=control(L"EDIT",L"",ES_AUTOHSCROLL|WS_TABSTOP);browseButton=control(L"BUTTON",L"Browse...",WS_TABSTOP,BROWSE);selectButton=control(L"BUTTON",L"Select",WS_TABSTOP,SELECT);refreshButton=control(L"BUTTON",L"Refresh",WS_TABSTOP,REFRESH);
    checkLabel=control(L"STATIC",L"Checks",0);checkCombo=control(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL|WS_TABSTOP);runButton=control(L"BUTTON",L"Run check",WS_TABSTOP,RUN);cancelButton=control(L"BUTTON",L"Cancel",WS_TABSTOP,CANCEL);EnableWindow(cancelButton,FALSE);logsButton=control(L"BUTTON",L"Open logs",WS_TABSTOP,LOGS);configButton=control(L"BUTTON",L"Settings file",WS_TABSTOP,CONFIG);
    actionLabel=control(L"STATIC",L"Git / GitHub",0);actionCombo=control(L"COMBOBOX",L"",CBS_DROPDOWNLIST|WS_VSCROLL|WS_TABSTOP);for(auto&a:actions){auto t=wide(a);SendMessageW(actionCombo,CB_ADDSTRING,0,(LPARAM)t.c_str());}SendMessageW(actionCombo,CB_SETCURSEL,0,0);remoteLabel=control(L"STATIC",L"Remote / first ref / owner/repo",0);remoteEdit=control(L"EDIT",L"origin",ES_AUTOHSCROLL|WS_TABSTOP);refLabel=control(L"STATIC",L"Branch / second ref / PR base",0);refEdit=control(L"EDIT",L"main",ES_AUTOHSCROLL|WS_TABSTOP);actionButton=control(L"BUTTON",L"Execute",WS_TABSTOP,ACTION);agentsButton=control(L"BUTTON",L"Agent guide",WS_TABSTOP,AGENTS);
    detailLabel=control(L"STATIC",L"Details: exact paths (one per line), commit message, remote URL, or PR title",0);detailsEdit=control(L"EDIT",L"",ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL|WS_TABSTOP);statusLabel=control(L"STATIC",L"Status / branches / worktrees",0);logLabel=control(L"STATIC",L"Live output - complete logs preserved on disk",0);auto style=ES_MULTILINE|ES_READONLY|ES_AUTOHSCROLL|ES_AUTOVSCROLL|WS_HSCROLL|WS_VSCROLL|WS_TABSTOP;statusEdit=control(L"EDIT",L"Select an SM64DS Git repository to begin.",style);logEdit=control(L"EDIT",L"Git, Python, GitHub CLI and build tools are external dependencies.\r\nNo ROM data is bundled.\r\n",style);SendMessageW(statusEdit,EM_SETLIMITTEXT,4*1024*1024,0);SendMessageW(logEdit,EM_SETLIMITTEXT,1024*1024,0);SendMessageW(logEdit,WM_SETFONT,(WPARAM)monoFont,TRUE);SendMessageW(statusEdit,WM_SETFONT,(WPARAM)monoFont,TRUE);activityLabel=control(L"STATIC",L"Ready - port-only safety is enabled by default.",0);set(repoEdit,settings.repository);SetTimer(h,1,200,nullptr);return 0;}
case WM_SIZE:layout(LOWORD(l),HIWORD(l));return 0;
case WM_GETMINMAXINFO:((MINMAXINFO*)l)->ptMinTrackSize={1000,680};return 0;
case WM_COMMAND:if(HIWORD(w)==BN_CLICKED){auto id=LOWORD(w);if(id==CANCEL){runner.cancel();set(activityLabel,"Cancelling process tree; complete partial log retained...");return 0;}if(busy)return 0;try{switch(id){case BROWSE:browse();break;case SELECT:selectRepo();break;case REFRESH:refresh();break;case RUN:runCheck();break;case ACTION:runAction();break;case LOGS:{auto p=dataDir/"logs";fs::create_directories(p);ShellExecuteW(h,L"open",p.c_str(),nullptr,nullptr,SW_SHOWNORMAL);break;}case CONFIG:ShellExecuteW(h,L"open",L"notepad.exe",config.c_str(),nullptr,SW_SHOWNORMAL);output("Settings reload at next launch. Use [checks] argv overrides; no shell expansion.\n");break;case AGENTS:start([]{Repository r(runner,repo,settings);auto text=r.agentHandoff();auto path=dataDir/"handoffs"/(uniqueId()+".txt");write(path,text);output(text+"\nSaved handoff: "+utf8(path.wstring())+"\n");});break;}}catch(const std::exception&e){MessageBoxW(h,wide(e.what()).c_str(),L"TangOS Lite",MB_OK|MB_ICONERROR);}}return 0;
case OUTPUT:{std::string p;{std::lock_guard<std::mutex> lock(outputMutex);p.swap(pending);}append(logEdit,p);return 0;}
case STATE:{auto*s=(std::string*)l;set(statusEdit,*s);delete s;set(repoEdit,settings.repository);fillChecks();return 0;}
case REVIEW:try{return reviewDialog(*(std::string*)l);}catch(...){return 0;}
case DONE:if(worker.joinable())worker.join();busy=false;EnableWindow(runButton,TRUE);EnableWindow(actionButton,TRUE);EnableWindow(cancelButton,FALSE);set(activityLabel,"Finished - inspect output and full log. Refresh status after Git changes.");if(smoke){if(smokePhase==1&&!repo.empty()&&!smokeExit){smokePhase=2;smokeTicks=0;PostMessageW(h,WM_COMMAND,RUN,0);}else if(smokePhase==2||smokeExit){auto screen=value(statusEdit);auto full=read(logPath);if(screen.find("main")==screen.npos||full.find("fixture.cpp:42")==full.npos||smokeTicks<3||value(logEdit).find("fixture.cpp:42")==std::string::npos)smokeExit=1;write(config.parent_path()/"gui-smoke-report.txt",std::string(smokeExit?"FAIL":"PASS")+" native window: repository selection, status, check execution, UI log, durable log, responsive timer ticks="+std::to_string(smokeTicks)+"\n"+screen+"\n"+full);smokePhase=3;PostMessageW(h,WM_CLOSE,0,0);}}return 0;
case WM_TIMER:if(smoke&&smokePhase==2)++smokeTicks;if(smoke&&smokePhase==0){smokePhase=1;PostMessageW(h,WM_COMMAND,SELECT,0);}return 0;
case WM_CLOSE:if(busy){runner.cancel();set(activityLabel,"Wait for cancellation to finish, then close.");return 0;}DestroyWindow(h);return 0;
case WM_DESTROY:PostQuitMessage(smokeExit);return 0;
}return DefWindowProcW(h,m,w,l);}
}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,PWSTR,int show){SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_SYSTEM32|LOAD_LIBRARY_SEARCH_USER_DIRS);SetSearchPathMode(BASE_SEARCH_PATH_ENABLE_SAFE_SEARCHMODE|BASE_SEARCH_PATH_PERMANENT);SetEnvironmentVariableW(L"GIT_TERMINAL_PROMPT",L"0");SetEnvironmentVariableW(L"PYTHONUNBUFFERED",L"1");CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);INITCOMMONCONTROLSEX init{sizeof(init),ICC_STANDARD_CLASSES};InitCommonControlsEx(&init);int argc;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);try{if(argc==4&&std::wstring(argv[1])==L"--verify-rom"){auto expected=trim(utf8(argv[3]));if(expected.size()!=64||expected.find_first_not_of("0123456789abcdefABCDEF")!=expected.npos)throw std::runtime_error("rom_sha256 must be a trusted 64-digit SHA256");for(auto&c:expected)c=(char)tolower((unsigned char)c);auto digest=sha256File(fs::path(argv[2]));std::cout<<"Local ROM SHA256: "<<digest<<"\n"<<(digest==expected?"Verified identity":"MISMATCH - obtain the correct version; do not distribute ROM data")<<"\n";LocalFree(argv);return digest==expected?0:1;}dataDir=localData();config=dataDir/"settings.ini";settings=loadSettings(config);if(argc==4&&std::wstring(argv[1])==L"--smoke-test"){smoke=true;settings.repository=utf8(argv[2]);config=fs::path(argv[3]);dataDir=config.parent_path()/"app-state";if(!fs::exists(fs::path(argv[2])/".tangos-lite-test-fixture"))throw std::runtime_error("Smoke test requires explicit fixture marker");settings=loadSettings(config);settings.repository=utf8(argv[2]);}if(!fs::exists(config))saveSettings(config,settings);
    WNDCLASSW wc{};wc.lpfnWndProc=ReviewProc;wc.hInstance=instance;wc.lpszClassName=L"TangOSLiteReview";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&wc);wc.lpfnWndProc=WindowProc;wc.lpszClassName=L"TangOSLite";wc.hIcon=LoadIconW(nullptr,IDI_APPLICATION);RegisterClassW(&wc);auto h=CreateWindowExW(0,wc.lpszClassName,L"TangOS Lite",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1180,820,nullptr,nullptr,instance,nullptr);if(!h)throw std::runtime_error("Cannot create native window");ShowWindow(h,show);UpdateWindow(h);if(!smoke&&!settings.repository.empty())PostMessageW(h,WM_COMMAND,SELECT,0);MSG msg;while(GetMessageW(&msg,nullptr,0,0)>0){if(!IsDialogMessageW(h,&msg)){TranslateMessage(&msg);DispatchMessageW(&msg);}}if(worker.joinable())worker.join();DeleteObject(uiFont);DeleteObject(monoFont);LocalFree(argv);CoUninitialize();return(int)msg.wParam;
}catch(const std::exception&e){if(argc>1&&std::wstring(argv[1])==L"--verify-rom"){std::cerr<<e.what()<<"\n";return 1;}MessageBoxW(nullptr,wide(e.what()).c_str(),L"TangOS Lite startup failed",MB_OK|MB_ICONERROR);return 1;}}


